default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: chordly_development

test:
  <<: *default
  database: chordly_test

production:
  <<: *default
  database: chordly_production
  username: postgres
  password: postgres
  host: chordly_db
